name: CI/CD Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Test-Node-Monolithic-SQL-REST-Learning-Management-System
    env:
      PORT: 3000
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      REDIS_URL: ${{ secrets.TEST_REDIS_URL }}
      # NODE_ENV: production

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm install
      - name: Debug ENV
        run: |
          echo "NODE_ENV=$NODE_ENV"
          echo "DATABASE_URL=$DATABASE_URL"
      - run: npm test
